/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tpimpal.view;

import java.awt.event.ActionListener;
import javax.swing.JButton;

/**
 *
 * @author Daniel
 */
public class MenuUtama extends javax.swing.JFrame {

    public JButton getBtnLogout() {
        return BtnLogout;
    }

    public void setBtnLogout(JButton BtnLogout) {
        this.BtnLogout = BtnLogout;
    }

    public JButton getBtnPenyewaan() {
        return BtnPenyewaan;
    }

    public void setBtnPenyewaan(JButton BtnPenyewaan) {
        this.BtnPenyewaan = BtnPenyewaan;
    }

    public JButton getBtnRiwayatPenyewaan() {
        return BtnRiwayatPenyewaan;
    }

    public void setBtnRiwayatPenyewaan(JButton BtnRiwayatPenyewaan) {
        this.BtnRiwayatPenyewaan = BtnRiwayatPenyewaan;
    }
    
    public void addListener(ActionListener e){
        BtnPenyewaan.addActionListener(e);
        BtnRiwayatPenyewaan.addActionListener(e);
        BtnLogout.addActionListener(e);
    }

    /**
     * Creates new form main_menu
     */
    public MenuUtama() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BtnPenyewaan = new javax.swing.JButton();
        BtnRiwayatPenyewaan = new javax.swing.JButton();
        BtnLogout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BtnPenyewaan.setText("Penyewaan");
        BtnPenyewaan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPenyewaanActionPerformed(evt);
            }
        });

        BtnRiwayatPenyewaan.setText("Lihat Riwayat Penyewaan");
        BtnRiwayatPenyewaan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRiwayatPenyewaanActionPerformed(evt);
            }
        });

        BtnLogout.setText("Logout");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(164, 164, 164)
                        .addComponent(BtnLogout))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addComponent(BtnRiwayatPenyewaan))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(156, 156, 156)
                        .addComponent(BtnPenyewaan)))
                .addContainerGap(124, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(BtnPenyewaan)
                .addGap(18, 18, 18)
                .addComponent(BtnRiwayatPenyewaan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                .addComponent(BtnLogout)
                .addGap(72, 72, 72))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnRiwayatPenyewaanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRiwayatPenyewaanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnRiwayatPenyewaanActionPerformed

    private void BtnPenyewaanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPenyewaanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnPenyewaanActionPerformed

    
    
    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnLogout;
    private javax.swing.JButton BtnPenyewaan;
    private javax.swing.JButton BtnRiwayatPenyewaan;
    // End of variables declaration//GEN-END:variables
}
